[build]
  publish = "out"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NEXT_PUBLIC_SUPABASE_URL = "https://placeholder.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "placeholder-key"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "demo-project"
