[build]
  publish = "out"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NEXT_PUBLIC_SUPABASE_URL = "https://qmrihkkuhxmihreoybxp.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtcmloa2t1aHhtaWhyZW95YnhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MjA4MDYsImV4cCI6MjA2OTI5NjgwNn0.lQQ2KorJF8Co2TaxqYxQGj4oxB5hJgHaSeIUTQGCIG4"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "demo-project"
